version: 2.1

executors:
  openjdk:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers
        environment:
          APP_NAME: password-updater
    working_directory: ~/password-updater

commands:
  package:
    steps:
      - run:
          name: package
          command: gradle build -x test
  docker_push:
    steps:
      - run:
          name: build image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: push image
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $IMAGE_NAME

jobs:
  validate_code:
    executor: openjdk
    steps:
      - checkout
      - restore_cache:
          key: $APP_NAME-{{ checksum "build.gradle" }}
      - package
      - save_cache:
          paths:
            - ~/.gradle
          key: $APP_NAME-{{ checksum "build.gradle" }}
          when: always
      - persist_to_workspace:
          root: build/libs
          paths:
            - ./

  push_image:
    executor: openjdk
    steps:
      - checkout
      - attach_workspace:
          at: build/libs
      - setup_remote_docker:
          docker_layer_caching: false
      - docker_push


workflows:
  version: 2
  password-updater_workflow:
    jobs:
      - validate_code
      - push_image:
          context: deploy
          requires:
            - validate_code
