version: 2.1

executors:
  openjdk:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers
        environment:
          APP_NAME: password-updater
    working_directory: ~/password-updater

commands:
  package:
    steps:
      - run:
          name: package
          command: gradle build -x test
  docker_push:
    steps:
      - run:
          name: Push image to docker hub
          command: |
            TAG_VERSION=$DOCKER_USERNAME/$IMAGE_NAME:v2.0.$CIRCLE_BUILD_NUM
            TAG_LATEST=$DOCKER_USERNAME/$IMAGE_NAME:latest
            docker build -t $TAG_VERSION -t $TAG_LATEST .
            docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
            docker push $TAG_VERSION
            docker push $TAG_LATEST

jobs:
  validate_code:
    executor: openjdk
    steps:
      - checkout
      - restore_cache:
          key: $APP_NAME-{{ checksum "build.gradle" }}
      - package
      - save_cache:
          paths:
            - ~/.gradle
          key: $APP_NAME-{{ checksum "build.gradle" }}
          when: always
      - persist_to_workspace:
          root: build/libs
          paths:
            - ./

  push_image:
    executor: openjdk
    steps:
      - checkout
      - attach_workspace:
          at: build/libs
      - setup_remote_docker:
          docker_layer_caching: false
      - docker_push


workflows:
  version: 2
  password-updater_workflow:
    jobs:
      - validate_code
      - push_image:
          context: deploy
          requires:
            - validate_code
